/**
 * ⚠️ STRICT SYNC: The 'value' strings below MUST exactly match 
 * the strings generated by the Python mDeBERTa NLP model.
 * The 'en' and 'ta' fields are the clean, short labels displayed on the UI.
 */

const departmentOptions = [
  {
    value: "Highways and Public Works Department (Roads, Potholes, Infrastructure, Pavement)",
    en: "PWD - Roads & Infrastructure",
    ta: "PWD - நெடுஞ்சாலை மற்றும் பொதுப்பணித்துறை"
  },
  {
    value: "Energy Department TANGEDCO (Electricity, Broken Wires, Power Poles, Transformers)",
    en: "TANGEDCO - Electricity",
    ta: "TANGEDCO - மின்சாரம்"
  },
  {
    value: "Municipal Administration and Water Supply (Garbage, Dead Animals, Fallen Trees, Sewage)",
    en: "MAWS - Water & Sanitation",
    ta: "MAWS - நகராட்சி மற்றும் குடிநீர் வழங்கல்"
  },
  {
    value: "Home Prohibition and Traffic Police (Illegal Parking, Vandalism, Law Enforcement)",
    en: "POLICE - Traffic & Law Enforcement",
    ta: "காவல்துறை - போக்குவரத்து மற்றும் சட்டம் ஒழுங்கு"
  }
];

function getLocalizedDepartmentLabel(value, language) {
  if (!value) return language === "ta" ? "பொது" : "General";

  // Search for the exact AI string
  const match = departmentOptions.find((item) => item.value === value);

  // If the AI spits out something weird, fallback to displaying the raw string
  if (!match) {
    return value;
  }

  // Return the clean, short localized label
  return language === "ta" ? match.ta : match.en;
}

export { departmentOptions, getLocalizedDepartmentLabel };